<a href="https://colab.research.google.com/github/nehagoyal09/Python_-Practice_Journey/blob/main/Day_7_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Slicing arrays**
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [ ]:
import numpy as np

arr = ([1, 2, 3, 4, 5, 6])      # Slicing 1D array

print(arr[1:5])                 # [start : end]
print(arr[:3])
print(arr[2:])
print(arr[::2])

print(arr[-3:])                # Last 3 elements
print(arr[:-2])                # Except last 2 elements

[2, 3, 4, 5]
[1, 2, 3]
[3, 4, 5, 6]
[1, 3, 5]
[4, 5, 6]
[1, 2, 3, 4]


In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])       # Slicing 2D array

print(arr[0:2, 1:4])                              # (row, column)

[[2 3]
 [5 6]]


In [ ]:
arr = np.array([[[11,12,13], [14,15,16], [17,18,19]],           # Slicing 3D array
                [[21,22,23], [24,25,26], [27,28,29]],
                [[31,32,33], [34,35,36], [37,38,39]]])          # block, row, column

print(arr[:2,1:,:2])

[[[14 15]
  [17 18]]

 [[24 25]
  [27 28]]]


# **View vs Copy**
Copy is a new array, and the View is just a view of the original array.

Any changes made to the copy will not affect original array.

Any changes made to the view will affect the original array.

In [12]:
import numpy as np               # Copy Method

arr = np.array([1, 2, 3, 4, 5])

copy = arr.copy()
copy[0] = 89

print(arr)
print(copy)

[1 2 3 4 5]
[89  2  3  4  5]


In [13]:
arr = np.array([1, 2, 3, 4, 5])

view = arr.view()
view[0] = 89

print(arr)
print(view)

[89  2  3  4  5]
[89  2  3  4  5]


**Append** (end में जोड़ना)

- Function: **np.append(array, values)**

 **Insert** (किसी index पर डालना)

 - Function: **np.insert(array, index, values)**

 **Delete Operations** (किसी index से हटाना)

 - Function: **np.delete(array, index)**

**[ use 2D]**

axis = 0 ( vertical direction) rows

axis = 1 (horizontal direction) columns


In [14]:
arr = np.array([1, 2,3])                # Append Method
new_arr = np.append(arr, [4,5,6])

print(arr)
print(new_arr)

[1 2 3]
[1 2 3 4 5 6]


In [22]:
arr = np.array([[1,2,3], [4,5,6]])         # axis = 0 (row)

print(np.append(arr, [7,8]))
print(np.append(arr, [[7,8,9]], axis=0))

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(np.append(arr, [[7], [8]], axis=1))  # axis = 1 (column)

[[1 2 3 7]
 [4 5 6 8]]


In [23]:
arr = np.array([1,2,3])             # Insert Method

print(arr)
print(np.insert(arr,1, [4,5]))


[1 2 3]
[1 4 5 2 3]


In [35]:
arr = np.array([[1,2], [3,4], [5,6]])

print(np.insert(arr, 2, [7,8]))
print(np.insert(arr,1, [11,12], axis=0))


[1 2 7 8 3 4 5 6]
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]


In [34]:
print(np.insert(arr,1, [11,12,13], axis=1))

[[ 1 11  2]
 [ 3 12  4]
 [ 5 13  6]]


In [36]:
arr = np.array([100,200,300,400])      # Delete Method
new_arr = np.delete(arr, 2)

print(arr)
print(new_arr)

[100 200 300 400]
[100 200 400]


In [39]:
arr = np.array([[ 1,  2,  3, 12],
               [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])


print(np.delete(arr,4))
print(np.delete(arr,1, axis=1))


[ 1  2  3 12  5  6 11  8  4 10  7]
[[ 1  3 12]
 [ 9  6 11]
 [ 8 10  7]]


In [40]:
print(np.delete(arr,1,axis=0))

[[ 1  2  3 12]
 [ 8  4 10  7]]


**Hstack vs Vstack**

- (Column) Hstack is used to join two arrays Horizontally.

   **np.hstack((arr1, arr2))**

- (Row) Vstack is used to join two arrays Vertically.

   **np.vstack((arr1, arr2))**   

In [43]:
import numpy as np              # Hstack method

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

h = np.hstack((arr_1, arr_2))
print(h)

[1 2 3 4 5 6]


In [44]:
v = np.vstack((arr_1, arr_2))    # Vstack Method
print(v)

[[1 2 3]
 [4 5 6]]


**Numpy Concatenation**

It is used for joining two or more arrays of the same shape along a specified axis.

**np.concatenate((arr1, arr2), axis=...)**

Axis = 0, Adding new rows

Axis = 1, Adding new columns

In [45]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]
