<a href="https://colab.research.google.com/github/nehagoyal09/Python_-Practice_Journey/blob/main/Day_6_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy Array Dimensions**
 **1D Array (Vector)**
- A 1D array is like a simple list of numbers.



**2D Array (Matrix)**
- A 2D array is like a table with rows and columns.



**3D Array (Tensor)**



- It has three axes: block, rows, and columns.



In [2]:
import numpy as np           # importing numpy libraray

In [ ]:
arr = np.array(5)       # scalar array
print(arr)

5


In [ ]:
print(arr.ndim)                  # Dimension Method
print(arr.shape)                 # Shape
print(arr.size)                  # Size

0
()
1


In [ ]:
arr1 = np.array([1,2,3,4,5])

print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                 [[7,8,9], [10,11,12]]])

print(arr3)
print(arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# **Python List vs Numpy Array**
- Python lists are Can store mixed types (int, float, string, etc.), but are slower for numerical operations 1D.

- NumPy arrays are homogeneous, memory-efficient, and optimized for mathematical and scientific computing and Supports multi-dimensional arrays (1D, 2D, 3D, …)

More Advantages of Numpy Array over list
- Array consumes less memory
- Array are faster than lists

In [8]:
List = [1, 3.9, 'apple']               # List = Different Datatypes
arr = np.array([1, 4, 6, 9])           # Array = Same Datatypes

# List
arr

array([1, 4, 6, 9])

In [9]:
arr = np.array([1.4, 7, 'apple'])       # Type conversation
arr

array(['1.4', '7', 'apple'], dtype='<U32')

In [10]:
List = [1, 2, 3, 4, 5]

print([x*2 for x in List])

[2, 4, 6, 8, 10]


In [11]:
arr = np.array([1, 2, 3, 4, 5])

print(arr*2)

[ 2  4  6  8 10]


# **Reshaping arrays**
Reshaping means changing the shape of an array.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)             # 1D to 2D array

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)            # 1D to 3D array

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,-1)                   # using -1 automatic calculation

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# **Array Indexing**
- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

In [26]:
arr = np.array([1, 2, 3, 4, 5])        # Accessing 1D array

print(arr[0])                         # First element
print(arr[3])                         # Fourth element
print(arr[2] + arr[4])

1
4
8


In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])          # Accessing 2D array

print(arr[1,4])                                    # (row, column)
print(arr[0,3])

10
4


In [30]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])       # Accessing 3D array

print(arr[0,1,2])                   # block, row , column
print(arr[1,1,2])

6
12
